### ISSUE TITLE
No module named 'VEnhancer'

### ISSUE THREAD

**Issue by ltx0633** [VikramxD/VEnhancer-ComfyUI-Wrapper#2]
Traceback (most recent call last):
  File "D:\work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\work\ComfyUI_windows_portable\ComfyUI\custom_nodes\VEnhancer-ComfyUI-Wrapper\__init__.py", line 3, in <module>
    from .nodes.single_gpu_loader import SingleGPUVEnhancerLoader
  File "D:\work\ComfyUI_windows_portable\ComfyUI\custom_nodes\VEnhancer-ComfyUI-Wrapper\nodes\single_gpu_loader.py", line 7, in <module>
    from VEnhancer.configs.venhnacer_config import VEnhancerConfig
ModuleNotFoundError: No module named 'VEnhancer'

Cannot import D:\work\ComfyUI_windows_portable\ComfyUI\custom_nodes\VEnhancer-ComfyUI-Wrapper module for custom nodes: No module named 'VEnhancer'

**Comment by VikramxD** [comment]
I don't have a windows Machine to test this , but maybe this solves it
```

cd D:\work\ComfyUI_windows_portable\ComfyUI\custom_nodes
git clone https://github.com/VikramxD/VEnhancer-ComfyUI-Wrapper.git
cd VEnhancer-ComfyUI-Wrapper
git clone https://github.com/VikramxD/VEnhancer.git
pip install setuptools
pip install -e . --no-build-isolation

```
